name: Release & Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure Git (if needed)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Install dependencies
        run: npm ci  # Or npm install if no lockfile

      - name: Bump version & generate changelog
        run: npx standard-version

      - name: Push version commit and tag
        run: |
          git push --follow-tags origin main

      - name: Build extension
        run: npm run compile

      - name: Publish to Visual Studio Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}
