name: Release & Publish

permissions:
  contents: write  # <-- This is essential to allow the push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Bump version & generate changelog
        run: |
          npx standard-version

      - name: Push version commit and tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push --follow-tags origin main

      - name: Build extension
        run: npm run compile

      - name: Publish to Visual Studio Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}
